### ISSUE TITLE
Validator slash - Nosia (23/03)

### ISSUE THREAD

**Issue by downlikedefi** [cennznet/app-faucet#57]
**(7) Validators targeted for slash on 23 March - They are requesting to restore slashed assets**

Validators went offline due to data centre failure 08:00 - 08:30 UTC, Nosia & KZK (node runners) 

No documentation to prove failure since period was short. Nosia & KZK requesting to increase offline sensitivity to 1 hour. 

The way I see it, data centre failure is not CENNZnet responsibility, but offline checks seemed to be a bit aggressive at the time. 

https://discord.com/channels/801219591636254770/965782173565218827

Action taken: Leave for governance to decide. 

Ticket-0029

**Comment by ken-futureverse** [comment]
@downlikedefi don't think this belong here and pretty sure we've resolved this

**Comment by downlikedefi** [comment]
wrong category, but theres a list of validators that did not get their slashes cancelled, we've promised to make that one of the first issues to be tackled by governance
